### GET REQUEST
GET http://localhost:48090/api/jsonBlob/1680055416514


### POST REQUEST
POST http://localhost:48090
content-type: application/json

{"test":"xxxxxxxxxxxxxxxxxxxxxxxxx"}


### PUT REQUEST
PUT http://localhost:48090/api/jsonBlob/test
content-type: application/json

{
	"hello":"world good"
}

### DELETE REQUEST
DELETE http://localhost:48090